// Exports contract ABIs from Foundry artifacts into @stipnd/protocol as TypeScript consts.
// Run after `forge build`: `pnpm --filter @stipnd/contracts abi:export`
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "out");
const target = join(here, "..", "..", "protocol", "src", "abi", "generated");
mkdirSync(target, { recursive: true });

const contracts = [
  { file: "StipendHub.sol/StipendHub.json", name: "stipendHubAbi" },
  { file: "MerchantRegistry.sol/MerchantRegistry.json", name: "merchantRegistryAbi" },
  { file: "MockUSD.sol/MockUSD.json", name: "mockUsdAbi" },
  { file: "MockIdentityRegistry.sol/MockIdentityRegistry.json", name: "mockIdentityRegistryAbi" },
];

const banner = "// Generated by packages/contracts/scripts/export-abi.mjs. Do not edit.\n";
const index = [];

for (const { file, name } of contracts) {
  const artifact = JSON.parse(readFileSync(join(outDir, file), "utf8"));
  const body = `${banner}export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(target, `${name}.ts`), body);
  index.push(`export { ${name} } from "./${name}";`);
  console.log(`wrote ${name} (${artifact.abi.length} entries)`);
}

writeFileSync(join(target, "index.ts"), `${banner}${index.join("\n")}\n`);
